name: django-mpesa

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master
jobs:
  build:
    env:
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      DEBUG: ${{secrets.DEBUG}}
      ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
      PASS_KEY: ${{secrets.PASS_KEY}}

    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Dependancies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: testing
        run: |
          python manage.py test
